### ISSUE TITLE
下拉刷新的时候会闪一下

### ISSUE THREAD

**Issue by dumingxin** [bihe0832/readhub-android#3]

**Comment by bihe0832** [comment]
嗯 ，目前的设计是下拉重新加载全新内容，上滑加载更多内容；因此下拉刷新时会清空所有历史重新加载，因此会出现闪一下的现象。后续优化一下这里的体验

**Comment by bihe0832** [comment]
目前已经开始了全新的开发分支，因为框架、UI等全替换了，因此这个问题可能会不再去修改了，非常抱歉~
